language: node_js
node_js:
  - "0.12"
services:
  # - neo4j
env:
  global:
    - GRAPHSTORY_URL=http://neo4j:neo4j@localhost:7474
jdk:
  - oraclejdk7
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
  - npm install -g gulp
cache:
  directories:
    - node_modules
